### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by DanRotaru** [webdev-sh/javascript-minifier.com#9]
![image](https://user-images.githubusercontent.com/7759507/99128062-7dfe0b80-2612-11eb-874f-b62f2814539c.png)

URL: https://javascript-minifier.com/raw

**Comment by christophboecker** [comment]
Same with me.

My code is
```php
<?php
$filename = 'xyz.js';
$content = file_get_contents($filename);
$minifier = 'https://javascript-minifier.com/raw';
$postdata = [
    'http' => [
        'method'  => 'POST',
        'header'  => 'Content-type: application/x-www-form-urlencoded',
        'content' => http_build_query( array('input' => $content) ),
    ]
];
$minified = file_get_contents($minifier, false, stream_context_create($postdata));
```

which results in these warnings:
```
Warning: file_get_contents(): SSL: Connection reset by peer in «path-to-file.php» on line 12
Warning: file_get_contents(): Failed to enable crypto in «path-to-file.php» on line 12
Warning: file_get_contents(https://javascript-minifier.com/raw): failed to open stream: operation failed in «path-to-file.php» on line 11
```
Testet on an iMac with macOS 10 (php 7.1) and today macOS 11 (php 7.3); same result.

**Comment by alorbach** [comment]
Same here, I have python script using this API and it times out most of the time :(

**Comment by alorbach** [comment]
Any chance to get this code running locally ? 
I am stuck here: 

```
#!/bin/bash

export APEX=localhost
export PORT=8021
export CODE_HOSTING_APEX=localhost
export CODE_HOSTING_ORG=

node server.js
```

> env: {
>   nodeEnv: undefined,
>   isDev: true,
>   isProd: false,
>   apex: 'localhost',
>   port: '8021',
>   baseUrl: 'http://localhost:8021',
>   locals: {
>     nodeEnv: undefined,
>     isDev: true,
>     isProd: false,
>     apex: 'localhost',
>     baseUrl: 'http://localhost:8021',
>     codeHostingApex: 'localhost',
>     codeHostingOrg: '',
>     codeHostingUrl: 'https://localhost//javascript-minifier.com',
>     googleAnalytics: undefined,
>     carbonServe: undefined,
>     carbonPlacement: undefined,
>     min: ''
>   }
> }
> level=info port=8021 evt=server-started
> node:events:306
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1128:16)
> Emitted 'error' event on RedisClient instance at:
>     at RedisClient.on_error (/mnt/d/!cvsroot/_Misc/javascript-minifier.com/node_modules/redis/index.js:406:14)
>     at Socket.<anonymous> (/mnt/d/!cvsroot/_Misc/javascript-minifier.com/node_modules/redis/index.js:279:14)
>     at Socket.emit (node:events:329:20)
>     at emitErrorNT (node:internal/streams/destroy:188:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:153:3)
>     at processTicksAndRejections (node:internal/process/task_queues:80:21) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379
> }

**Comment by alorbach** [comment]
nevermind I got it running by installing missing redis-server packages.

**Comment by christophboecker** [comment]
Trying to connect via firefox to https://javascript-minifier.com/raw 
gives me a Message
<img width="856" alt="grafik" src="https://user-images.githubusercontent.com/10065904/99416087-c52d1a80-28f8-11eb-9ebe-3e004f38034b.png">
The last sentence translated from German is 'The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.' this leads imho to an error description pointing to the TLS version used on the server.
https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect

**Comment by alorbach** [comment]
@christophboecker: The server appears to be broken - not maintained anymore.
I would recommend to do as I did, clone the repositories and set up local servers, I have used Ubuntu 18. 
Get latest nodejs and these packages: 
```
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
apt-get install -y nodejs npm
apt-get install gcc g++ make redis-server supervisor
```

Then clone this repo here > https://github.com/webdev-sh/javascript-minifier.com/ < and run **make** in it. 

After it is done, you can start a local server using this script: 
```
#!/bin/bash

export APEX=localhost
export PORT=8021
export CODE_HOSTING_APEX=localhost
export CODE_HOSTING_ORG=javascript-minifier
npm run dev-server
```

Hope this helps.

**Comment by christophboecker** [comment]
Thanks @alorbach, good idea. In parallel I found a PHP-Script doing the job on a level, which is sufficient for me and easy to integrate in my code-base. I´ll  go this way.
